INSERT INTO USER(USER_ID, USER_NAME) VALUES (USER_SEQ.nextVal, 'Wojtek');
INSERT INTO USER(USER_ID, USER_NAME) VALUES (USER_SEQ.nextVal, 'Marek');

INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (CAR_SEQ.nextVal, 'BMW', 'PRIVATE');
INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (CAR_SEQ.nextVal, 'AUDI', 'PRIVATE');
INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (CAR_SEQ.nextVal, 'HONDA', 'PUBLIC');
INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (CAR_SEQ.nextVal, 'TOYOTA', 'PRIVATE');

INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 1);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 2);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 3);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (2, 3);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (2, 4);

INSERT INTO LAYOUT(LAYOUT_ID, LAYOUT_NAME, CAR_ID) VALUES (LAYOUT_SEQ.nextVal, 'Layout 1', 1);
INSERT INTO LAYOUT(LAYOUT_ID, LAYOUT_NAME, CAR_ID) VALUES (LAYOUT_SEQ.nextVal, 'Layout 2', 2);
