INSERT INTO USER(USER_ID, USER_NAME) VALUES (1, 'Wojtek');
INSERT INTO USER(USER_ID, USER_NAME) VALUES (2, 'Marek');

INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (1, 'BMW', 'PRIVATE');
INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (2, 'AUDI', 'PRIVATE');
INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (3, 'HONDA', 'PUBLIC');
INSERT INTO CAR(CAR_ID, CAR_MODEL, CAR_TYPE) VALUES (4, 'TOYOTA', 'PRIVATE');

INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 1);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 2);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 3);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (2, 3);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (2, 4);

INSERT INTO LAYOUT(LAYOUT_ID, LAYOUT_NAME, USER_ID) VALUES (1, 'Superb', 1);
INSERT INTO LAYOUT(LAYOUT_ID, LAYOUT_NAME, USER_ID) VALUES (2, 'Octavia', 1);
INSERT INTO LAYOUT(LAYOUT_ID, LAYOUT_NAME, USER_ID) VALUES (3, 'Golf', 2);
