INSERT INTO USER(USER_ID, USER_NAME) VALUES (1, 'Wojtek');
INSERT INTO USER(USER_ID, USER_NAME) VALUES (2, 'Marek');
INSERT INTO USER(USER_ID, USER_NAME) VALUES (3, 'Janek');
INSERT INTO USER(USER_ID, USER_NAME) VALUES (4, 'Kasia');
INSERT INTO USER(USER_ID, USER_NAME) VALUES (5, 'Agnieszka');

INSERT INTO CAR(CAR_ID, CAR_MODEL) VALUES (1, 'BMW');
INSERT INTO CAR(CAR_ID, CAR_MODEL) VALUES (2, 'AUDI');
INSERT INTO CAR(CAR_ID, CAR_MODEL) VALUES (3, 'HONDA');
INSERT INTO CAR(CAR_ID, CAR_MODEL) VALUES (4, 'TOYOTA');
INSERT INTO CAR(CAR_ID, CAR_MODEL) VALUES (5, 'VOLKSWAGEN');

INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 1);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (1, 2);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (2, 3);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (2, 4);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (3, 5);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (4, 4);
INSERT INTO USER_CAR(USER_ID, CAR_ID) VALUES (4, 5);

